//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoodEats.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GoodEats.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alright, you&apos;re all set for **{0}** on **{1}** at **{2}**.  I hope you have a great time!  Good-bye!.
        /// </summary>
        internal static string BOOKED_CONFIRMATION {
            get {
                return ResourceManager.GetString("BOOKED_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK, I&apos;ll be here if you need me.  Good-bye!.
        /// </summary>
        internal static string CANCEL_CONFIRMATION {
            get {
                return ResourceManager.GetString("CANCEL_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got it.
        /// </summary>
        internal static string CONFIRMATION {
            get {
                return ResourceManager.GetString("CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sorry, I didn&apos;t understand your repsonse.  Click the **Reserve** button to confirm your reservation..
        /// </summary>
        internal static string CONFIRMATION_UNRECOGNIZED {
            get {
                return ResourceManager.GetString("CONFIRMATION_UNRECOGNIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alright, let&apos;s see what we can find..
        /// </summary>
        internal static string CUISINE_CONFIRMATION {
            get {
                return ResourceManager.GetString("CUISINE_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What type of food are you in the mood for?.
        /// </summary>
        internal static string CUISINE_REQUEST {
            get {
                return ResourceManager.GetString("CUISINE_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hmm, I can&apos;t seem to find any any *{0}* restaurants in your area.  Here are some options that I did find:.
        /// </summary>
        internal static string CUISINE_UNRECOGNIZED {
            get {
                return ResourceManager.GetString("CUISINE_UNRECOGNIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sure, I can help you with that..
        /// </summary>
        internal static string GREETING {
            get {
                return ResourceManager.GetString("GREETING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alright, **{0}** it is. I&apos;ll look for options in  your area..
        /// </summary>
        internal static string LOCATION_CONFIRMATION {
            get {
                return ResourceManager.GetString("LOCATION_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where will you be eating?  I&apos;ll look for restaurants in your area..
        /// </summary>
        internal static string LOCATION_REQUEST {
            get {
                return ResourceManager.GetString("LOCATION_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hmm, I can&apos;t seem to find any restaurants in that area.  What other city or town could I try?.
        /// </summary>
        internal static string LOCATION_UNRECOGNIZED {
            get {
                return ResourceManager.GetString("LOCATION_UNRECOGNIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sorry, I didn&apos;t understand.  You can ask me things like &apos;make me a reservation in Pittsburgh next Friday at 8:30 pm&apos;, or &apos;I&apos;d like to make a reservation at an italian restaurant in Miami FL&apos;..
        /// </summary>
        internal static string NONE {
            get {
                return ResourceManager.GetString("NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many people will be in your party?.
        /// </summary>
        internal static string PARTY_REQUEST {
            get {
                return ResourceManager.GetString("PARTY_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got it!.
        /// </summary>
        internal static string PARTY_SIZE_CONFIRMATION {
            get {
                return ResourceManager.GetString("PARTY_SIZE_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sorry, I didn&apos;t catch that.  How many people should I include on the reservation?.
        /// </summary>
        internal static string PARTY_UNRECOGNIZED {
            get {
                return ResourceManager.GetString("PARTY_UNRECOGNIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK, here&apos;s what I have.  Click &apos;Reserve&apos; to confirm your reservation..
        /// </summary>
        internal static string RESERVATION_CONFIRMATION {
            get {
                return ResourceManager.GetString("RESERVATION_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sounds good...**{0}** it is!.
        /// </summary>
        internal static string RESTAURANT_CONFIRMATION {
            get {
                return ResourceManager.GetString("RESTAURANT_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are some **{0}** restaurants I found near *{1}*:.
        /// </summary>
        internal static string RESTAURANT_REQUEST {
            get {
                return ResourceManager.GetString("RESTAURANT_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sorry, but I can&apos;t find *{0}*.  Here are some restaurants I did find in *{1}*:.
        /// </summary>
        internal static string RESTAURANT_UNRECOGNIZED {
            get {
                return ResourceManager.GetString("RESTAURANT_UNRECOGNIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got it.  I&apos;ll book the reservation for **{0}** at **{1}**.
        /// </summary>
        internal static string WHEN_CONFIRMATION {
            get {
                return ResourceManager.GetString("WHEN_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When will you be eating?.
        /// </summary>
        internal static string WHEN_REQUEST {
            get {
                return ResourceManager.GetString("WHEN_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sorry, I didn&apos;t understand you.  When did you plan to eat?  I just need to know the day and time..
        /// </summary>
        internal static string WHEN_UNRECOGNIZED {
            get {
                return ResourceManager.GetString("WHEN_UNRECOGNIZED", resourceCulture);
            }
        }
    }
}
